### ISSUE TITLE
I'm stuck. I need a mentor to review my work.

### ISSUE THREAD

**Issue by jucie** [exercism/support#28]
My issue is simple. I need for some mentor to review my submission, otherwise I can't proceed.
Track Rust, exercise Bob.
Thanks.

**Comment by Naphier** [comment]
I've been waiting for 56 days on JavaScript / Matrix exercise review. Nearly forgot that I'd been using exercism. Please help :)

**Comment by SleeplessByte** [comment]
Hi @Naphier . Oof yes. That's an exercise that's hard to mentor! I'm sorry you've been stuck for so long. We are actually working hard on solving this. See [countdown.exercism.io](https://countdown.exercism.io/) for more information.

If you post your solution URL here, we can make sure someone picks it up.

**Comment by Naphier** [comment]
https://exercism.io/my/solutions/8ae57e732c544f619f2dbfe2c9e4f5a4
Thanks! I don't mind waiting for feedback but being locked = losing interest. Appreciate the help.

**Comment by Naphier** [comment]
@SleeplessByte 
It's now been nearly another 2 weeks. Surely an admin can just mark it reviewed or something? I've now been waiting 70 days. This is silly.  😞

**Comment by emcsquared2** [comment]
Hi!
I'm very much in the early stages of coding but have a decent grasp of the basics of JS.  I thought Exercism would be a really great place to improve my skills but it is so frustrating.  What do I do if I get stuck!?  Can you only ask a question from a mentor if you've already completed the exercise?  Is there no community support either?  I might be missing something obvious but I cannot find a way of getting help! 

It would be helpful to be able to see the solution to work out why I am failing to pass a particular test.  There is no obvious way of getting feedback.  For example with codewars you can view the solution (but you just don't earn your kyu).

I'm on the Elyses Enchantments and I'm getting a failed test around removing a card from the stack (Array).  I know exactly how to manipulate arrays in JS and have no clue why it is failing. 

If I was just able to view the solutions without passing all the tests I would be able to work it out.

Please help!

**Comment by SleeplessByte** [comment]
@emcsquared2 the concept exercise / learning exercises are really designed to be completed _without_ looking at the results before you ask for mentorship (unlike the practice exercises). They should be relatively trivial for those with a background in (a different) programming (language).

Exercism isn't great to teach you _programming_, mostly because our goal is to help people gain fluency in a new programming language.

That said, if the exercise isn't giving you information on why it's failing, then that's probably not great. Downloading your exercise using the CLI and seeing the full error locally might help here. You can also submit incomplete/failing submission using the CLI.

**Comment by emcsquared2** [comment]
![Screenshot_20210924-071204](https://user-images.githubusercontent.com/72265437/134626836-086d5658-e84c-4531-8f56-c5ea4d028593.png)

Thank you for responding @SleeplessByte. I don't know if you work for exercism or you are a contributor. 

So I'm at the point where I am fairly fluent in JS and I've had this recommended to me. I'm self taught and it is really challenging when you are on your own.

Attaching screenshot above with error messages. I've got everything right except for the two remaining errors. The feedback doesn't even make sense to me.  I feel like I am just at the right stage for exercism now. It's really hard working new stuff out on your own. The only way to learn when you are a newbie is to look at the solution when you are completely stuck so you can work out where you went wrong. 
As in the example above, the links to the Array method on MDN are no help because you need to be able to figure that bit out yourself. 

What is the rationale behind not revealing the solutions?!  It makes no sense educationally. 

All that said I will attempt using the CLI as you say. Thank you for pointing me in that direction. It's really not clear on the website that you can submit incomplete answers. Why can't you do that online 🤷‍♂️. 

Sorry for the frustration, I'm determined to get my head around this because I can see it will really help my development and ironically all I need is a little bit of mentoring.

**Comment by SleeplessByte** [comment]
@iHiD can probably chime in here and help you understand the rationale behind these decisions.

Here is what I would have said if I had given you actual mentorship:

> ## Error messages
>
> Let's have a look at the first failing test: **remove the card at the top**
>
> ### Code run
> 
> ```javascript
> const stack = [1, 2, 3, 4]
> const position = 3
> const expected = [1, 2, 3]
>
> expect(removeItem(stack, position)).toStrictEqual(expected)
> ```
>
> This is the JavaScript code that the test runner runs.
> It expects that given the input `stack` and `position`, `expected` is the result
>
> ### Test Failure
>
> ```diff
> - Expected  - 1
> + Received  + 1
>
>   Array [
> -   1
>     2
>     3
> +   4
>   ]
>```
>
> This is trying to show you the difference between what was actually returned and what was expected.
> In actuality, it returned `[2, 3, 4]`, but it wanted `[1, 2, 3]`. 
> So the item `1` is missing (`-`) and the item `4` is extraneous.
>
> ### Working out how to solve this
>
> How could this happen?
> One of the ways this could happen if item `3` isn't actually removed, but item `0` is.
> Another way this could happen is if items are counted from right to left.
>
> The code that is triggered is:
>
> ```javascript
> function removeItem(cards, position) {
>   cards.shift();
>   return cards;
>   throw new Error('Implement the removeItem function');
> }
> ```
>
> It looks like `position` is not used at all.
> Which card is removed when `cards.shift()` is called?
>
> You can use `console.log(/*...*/)` to log debug information from the test-runner to the test output.

**Comment by iHiD** [comment]
Learning Exercises should be solvable without needing to see a solution or get mentoring. The hints should give enough information that if you get stuck, you can always find a way out through them. Practice Exercises are a bit different, but for these it sounds like we need to tweak the hints a bit to give you a route to safety.

To answer your specific questions.

> What is the rationale behind not revealing the solutions?! It makes no sense educationally.

Well, I'm not sure it makes no sense. If you give someone the solution they're likely to reach for it when they get stuck rather than really wrestling with the problem to learn. From my experience the real learning-points in coding happen when you've been stuck on something for ages and have to go deep into it from first-principles to solve the problem. That strengthens so much knowledge in your head and let's you see things differently. So we want to make it a little hard to solve things. As I said above, Concept Exercises should be always solvable though.

> All that said I will attempt using the CLI as you say. Thank you for pointing me in that direction. It's really not clear on the website that you can submit incomplete answers. Why can't you do that online 🤷‍♂️.

Because we'd be flooded with beginners who have zero-barrier to request mentoring. The CLI has always provided a guard to ensure that people using exercism are not total beginners. With the addition of the online editor that barrier has been removed, which is great in some senses, but also risks overwhelming our mentors if anyone can then get handholding through exercises when they don't have the prerequisite programming knowledge.

Also, mentoring isn't really about solving the exercises - it's about improving working code to make it idiomatic. As a general rule, we want people to go through the "pain" of solving something and learning lots, and then working with a mentor to discover the bits they don't know they don't know.

---

All that said, there's maybe/probably something we should do to improve things here. Potentially once you've got some tests running, but can't get all of them running, we open up the solutions for people, or let you request mentoring. I'd need to think hard about that, but being frustrated isn't the objective here.

Good work out persistence! 🙂

**Comment by emcsquared2** [comment]
@SleeplessByte Thank you so much for your feedback.  I have a background in education, taken a career break and now looking to career switch.  I have a lot to thank for people like you.  Much appreciated.

Just in terms of feedback on this particular question @SleeplessByte and @iHiD it was a silly mistake that threw me (although I did learn some extra stuff from your feedback @SleeplessByte which was terrific.  Thank you!  I will be good enough to be a mentor one day).   It was the comment "Remove the card at the 0-based position".  Hence my confusion and using .shift()

`/**
 * **Remove the card at the 0-based position**
 *
 * @param {number[]} cards
 * @param {number} position
 *
 * @returns {number[]} the cards without the removed card
 */
export function removeItem(cards, position) {
  cards.splice(position, 1);
  return cards;
  throw new Error('Implement the removeItem function');
}`

@iHiD I totally respect this awesome product and am sincerely grateful for a really cool resource. You must be proud of what you have achieved. However I fundamentally disagree with making it hard to access the solutions.  I didn't get to my level of knowledge in coding today being spoon fed.  I hunted down the answers and worked it out myself.  I managed to do everything here including downloading a CLI all by myself for the first time.  Having spent most of my life working in education the idea that holding the answers back from people is somehow helping them feels to me to be quite patronising to be honest.  I think this example is case in point.  Were I able to view the solution online, I could have worked it out myself without the need for mentoring.  (although totally appreciated it) Then I can use mentoring for some proper meaty stuff down the line.  You never know it might stem the flow of mentoring questions as well.  If you're worried about people picking up bad habits then maybe provide the model answer as the solution?

I can tell you for a fact that the real power in mentoring is when you have looked hard at the answers and studied them closely and you are still stuck.  Then you get help.

**Comment by emcsquared2** [comment]
One other piece of feedback was that I did kinda need this video to get me over the finish line with the CLI bit https://www.youtube.com/watch?v=T5WUJ-WhSZ4
If you were able to do your own that would be neat.

It was quite exciting to get it running on my local machine, even if I didn't fully understand everything that was going on.

You guys are awesome.  Have a good weekend
David

**Comment by iHiD** [comment]
> I can tell you for a fact that the real power in mentoring is when you have looked hard at the answers and studied them closely and you are still stuck. Then you get help.

You sound like a person with great self-efficacy. My experience is that many people do not have that same level of willingness to push themselves to find a solution themselves and tend to reach for the answer when we provide it. Our experience shows that when people see the solutions beforehand, they often just copy them in without understanding what is going on, then are really confused during mentoring. Exercism is very different to a formal education setting where people are in a high-commitment mindset.

As a side note, you can access the solutions via the URL - the button just doesn't exist. So you (personally) can use them now you know that.

**Comment by emcsquared2** [comment]
That is very interesting. I take your point completely. I hadn't thought of it like that.

Huh. Cool. Thanks.

**Comment by SleeplessByte** [comment]
Since we're now in V3, perhaps I close this issue :P
