### ISSUE TITLE
Mentor Feedback Expectations

### ISSUE THREAD

**Issue by civrot** [exercism/support#37]
Hi,

I was just wondering what the expectations on the time for a mentor to provide feedback is. I just started going through the ruby track.  Initially I was getting feedback on my solutions within a few hours and I was moving through the track. My last submission was two days ago, and still no feedback.  I am essentially stalled on the main track.  I understand that this a free service for individuals and I really do appreciate it. I think you are doing great things here. I was enjoying working through the track and want to continue.  

Thanks

**Comment by NobbZ** [comment]
Times can get very long, this massively depends on the track you are on, also I have to be honest to you, the further you progress the longer you'll have to wait for feedback, as fewer and fewer mentors also have done the exercise and most mentors follow the unwritten rule to not mentor exercises they haven't solved themselves.

But since a couple of days you can find an estimation of your current queue position on the exercises page.
