### ISSUE TITLE
make test fails in c track on windows

### ISSUE THREAD

**Issue by BRobersonO** [exercism/support#40]
I'm reasonably confident I have the c compiler pointed to in the path in environmental variables.
Yet when I run make in the Windows Command Prompt when I'm in the correct exercise directory I get an error saying the system cannot find the file specified. I have both a .c and an .h file in the src directory. Any ideas?

C:\Users\BRobersonO\Exercism\c\word-count>make
Compiling tests.out
process_begin: CreateProcess(NULL, cc -std=c99 -g -Wall -Wextra -pedantic -Werror -DUNITY_SUPPORT_64 src/*.c test/vendor/unity.c test/*.c -o tests.out -lm, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [tests.out] Error 2

When I try the same thing with Ubuntu, I get:

brobersono@BRobersonO-PC:/mnt/c/users/BRobersonO/Exercism/c/word-count$ make
Compiling tests.out
/bin/sh: 1: cc: not found
makefile:32: recipe for target 'tests.out' failed
make: *** [tests.out] Error 127

**Comment by NobbZ** [comment]
@BRobersonO Sorry that there hasn't anyone responded during the last months…

The issue probably didn't appear on our radar before, since it was posted to the issue tracker for the `exercism` CLI tool, not the usual centralized issue tracker.

But due to the big triage happening right now, awareness was higher ;)

So please let us ask some questions about your system.

* When you said you installed a C compiler, which one was it?
  * Did you install it under windows or ubuntu?
  * Could you please show us the `PATH` variables content?
* When you speak about ubuntu, do you mean WSL ubuntu or a VM or a dualboot?

But from the error messages you have posted it seems as if there is no C compiler in `PATH` (or not the correct one…)

**Comment by ShockvaWe** [comment]
Is exercism not compatible with windows? I am using mingw-w64 as a compiler.
I downloadede the first test case which is hello-world.
When I try to make it gives this error:
`Compiling tests.out
/usr/bin/sh: cc: command not found
make: *** [makefile:34: tests.out] Error 127`
Then I looked to the makefile and saw that its all linux commands.
Then I edited makefile and added cc=gcc CC=gcc and now it gives this error:
` make test
Compiling tests.out
src/hello_world.c: In function 'hello':
src/hello_world.c:5:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1.exe: all warnings being treated as errors
make: *** [makefile:36: tests.out] Error 1`

It seems like I am going to learn C from old ways too many problems for me.

**Comment by NobbZ** [comment]
@shockwave please file an issue in the [C repository](https://github.com/exercism/c) because of the compiler name.

The other error is kind of expected, as the provided stub of the function is declared to return `char*`, but has an empty body which you need to fill in as student to make the function do the right thing.

**Comment by ShockvaWe** [comment]
@NobbZ Yes, I figured it out and completed the case with succes. Thanks for your comment anyways.
This is not a place but I think I won't use exercism anymore because the second test case is like a question from hackerrank, I wanted to learn c programming not sharpening my skills or developing my problem solving skillz.

**Comment by BRobersonO** [comment]
Solved awhile ago. Sorry I haven't updated.

I was working on another project in C and was having trouble. I found an answer to help me fix that issue. If I remember correctly, there were two folders named "mingw32" and I had to change one of them to "mingw32old". Here's the link to what I used (see the second answer): https://stackoverflow.com/questions/30147411/as-exe-entry-point-not-found-the-procedure-entry-point-printf-could-not-be

Anyway, I thought to myself "Hm, I wonder if that was causing my testing issue with exercism." Sure enough, I can now run the test using the command "mingw32-make test". Not %100 sure it's because of this change, but it works now.
