### ISSUE TITLE
Email confirmation email never sent

### ISSUE THREAD

**Issue by jpotier** [exercism/support#69]
![image](https://user-images.githubusercontent.com/752510/65385195-4d835000-dd34-11e9-96da-1ca9304c9457.png)

I tried several time and never actually received any email, over the course of a day. How many minutes should I wait?

My email server actually never was sent anything from exercism.io (maybe you're using a relay I don't know of).

**Comment by sshine** [comment]
@iHiD, @jpotier: This is an unfortunate situation, but seeing as a week has passed, perhaps the honest conclusion we might have to make at this point is that @iHiD is the only person with the privilege to check the mail spool, and he's also the head of the project and so has very limited resources to handle single support requests that require this kind of digging.

An alternative path that may have less resistance could be for @jpotier to change his GitHub default email address to a common email provider we successfully send emails to daily, e.g. Gmail, and have @iHiD update the email we cache from GitHub (I don't remember if the website does this automatically yet), and see if resetting works then.

This is not ideal, but perhaps doable within reasonable time.

**Comment by iHiD** [comment]
Thanks @sshine 💙 

@jpotier Our SMTP provider automatically adds emails that bounce to a suppression list so as not to reduce our deliverability rates. I've removed your email from our suppression list, so it should now work if you re-request.

If that doesn't work, then I suggest you sign up with GitHub as per @sshine's suggestion, rather than waiting for me to find time to debug for you. Hopefully the former suggestion should work though :)

**Comment by sshine** [comment]
I'm closing this issue, but let us know if you're still stuck, @jpotier.
